export declare enum FormEvent {
    TOKEN_CREATION = "TOKEN_CREATION",
    FORM_RESET = "FORM_RESET",
    PAN_PAYLOAD = "PAN_PAYLOAD",
    FORM_INITIALIZED = "FORM_INITIALIZED",
    ONE_CLICK_PAYMENT_SUBMIT = "ONE_CLICK_PAYMENT_SUBMIT",
    SUBMIT_CLICKED = "SUBMIT_CLICKED",
    FORM_RESPONSE = "FORM_RESPONSE",
    INIT_SONGBIRD = "INIT_SONGBIRD",
    START_CCA = "START_CCA",
    START_BIN_PROCESS = "START_BIN_PROCESS",
    CONTINUE_CCA = "CONTINUE_CCA"
}
